# .github/workflows/deploy.yml
name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before deployment
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.c39c142c6bb9fd3a1cfbec8e4e4c8ffd }}
        RENDER_SERVICE_ID: ${{ secrets.7086f101054dbfba62c7707959d6cdc1 }}
      run: |
        curl -X POST "https://api.render.com/v1/services/$7086f101054dbfba62c7707959d6cdc1/deploys" \
        -H "Authorization: Bearer $c39c142c6bb9fd3a1cfbec8e4e4c8ffd" \
        -H "Content-Type: application/json"